version: 2
jobs:
  build:
    docker:
      - image: jetcipher/circleci-dotnet-core:3.1
    steps:
      - checkout
      - run:
          name: Restore
          command: dotnet restore
          working_directory: src
      - run:
          name: Build
          command: dotnet build Dotnet.Youtube.WatcherResponder.sln -c Release
          working_directory: src
      - run:
          name: Running Tests
          command: dotnet test Dotnet.Youtube.WatcherResponder.sln
          working_directory: tests
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push Docker image
          command: |
            docker build -t Dotnet.Youtube.WatcherResponder .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker tag boku zabralex85/Dotnet.Youtube.WatcherResponder
            docker push zabralex85/Dotnet.Youtube.WatcherResponder