version: 2.1

orbs:
  win: circleci/windows@1.0.0

jobs:
  build:
    executor:
      name: win/vs2019
      shell: powershell.exe
    steps:
      - checkout
      - restore_cache:
          keys:
            - dotnet-packages-v1-{{ checksum "Dotnet.Youtube.WatcherResponder.sln" }}
      - run:
          name: "Install project dependencies"
          command: dotnet.exe restore Dotnet.Youtube.WatcherResponder.sln
          working_directory: src
          
      - save_cache:
          paths:
            - C:\Users\circleci\.nuget\packages
          key: dotnet-packages-v1-{{ checksum "Dotnet.Youtube.WatcherResponder.sln" }}

      - run:
          name: "Run Build step"
          command: dotnet.exe publish Dotnet.Youtube.WatcherResponder.sln -c Release -r win10-x64
          working_directory: src

      - store_artifacts:
          path: .\bin\Release\netcoreapp2.1\win10-x64\publish\Dotnet.Youtube.WatcherResponder.exe