version: 2.0
jobs:
 build:
   docker:
     - image: mcr.microsoft.com/dotnet/core/sdk:3.1
   steps:
     - checkout
     - run:
         name: Restore packages
         command:
           dotnet restore
         working_directory: src
     - run:
         name: Build App
         command:
           dotnet build -c Release -o Release
         working_directory: src